INSERT INTO homestead.dishes (id, dish, price, image, ingredients) VALUES (1, 'Nemo neque', 6.18, '1.jpg', 'Sit, Quidem, Et, Odio amet');
INSERT INTO homestead.dishes (id, dish, price, image, ingredients) VALUES (2, 'Quas', 25.66, '2.jpg', 'Autem, Quae, Nihil, Et a');
INSERT INTO homestead.dishes (id, dish, price, image, ingredients) VALUES (3, 'Voluptatem', 21.49, '3.jpg', 'Quia, Mollitia, Quia quae, Corporis');
INSERT INTO homestead.dishes (id, dish, price, image, ingredients) VALUES (4, 'Voluptatem in', 12.48, '4.jpg', 'Quis ut, Nostrum, Id animi, Placeat');
INSERT INTO homestead.dishes (id, dish, price, image, ingredients) VALUES (5, 'Dolore rerum', 36.54, '5.jpg', 'Maxime, Inventore, Atque aut, Culpa ad');
INSERT INTO homestead.dishes (id, dish, price, image, ingredients) VALUES (6, 'Aperiam', 21.56, '6.jpg', 'Magni, Quam, Sit velit, Corporis');
INSERT INTO homestead.dishes (id, dish, price, image, ingredients) VALUES (7, 'Adipisci non', 15.53, '7.jpg', 'Autem, Officia, Et, Sit quia');
INSERT INTO homestead.dishes (id, dish, price, image, ingredients) VALUES (8, 'Id repellat ut', 13.68, '8.jpg', 'Id, Est aut, Quia, Magnam');
INSERT INTO homestead.dishes (id, dish, price, image, ingredients) VALUES (9, 'Facere harum', 27.86, '9.jpg', 'Qui, Eveniet, Quis est, Provident');
INSERT INTO homestead.dishes (id, dish, price, image, ingredients) VALUES (10, 'Eos vero', 15.52, '10.png', 'Optio est, Nisi, Minnus, In ea id');
INSERT INTO homestead.dishes (id, dish, price, image, ingredients) VALUES (11, 'Qui id', 37.98, '11.jpg', 'Atque, Rerum hic, Sit quia, Aut');
INSERT INTO homestead.dishes (id, dish, price, image, ingredients) VALUES (12, 'Temporibus', 3.99, '12.jpeg', 'Non esse, Vero et, Possimus, Est');
INSERT INTO homestead.dishes (id, dish, price, image, ingredients) VALUES (13, 'Voluptas', 11.33, '13.jpg', 'Ut, Earum, Animi, Officia');
INSERT INTO homestead.dishes (id, dish, price, image, ingredients) VALUES (14, 'Quo non quis', 22.99, '14.jpg', 'Sint hic, Alias et, Pariatur, Iste et');
INSERT INTO homestead.dishes (id, dish, price, image, ingredients) VALUES (15, 'Id placeat sed', 19.32, '15.jpg', 'Quasi, Ullam non, Quaerat, Aperiam');
INSERT INTO homestead.migrations (id, migration, batch) VALUES (1, '2014_10_12_000000_create_users_table', 1);
INSERT INTO homestead.migrations (id, migration, batch) VALUES (2, '2014_10_12_100000_create_password_resets_table', 1);
INSERT INTO homestead.migrations (id, migration, batch) VALUES (3, '2018_09_08_221450_pizza', 1);
INSERT INTO homestead.migrations (id, migration, batch) VALUES (4, '2018_09_09_134425_create_dishes', 2);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (17, 'Porro beatae', 'Sed qui, Quaerat, Suscipit, Ipsum', 15.59);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (18, 'Eos voluptatem', 'Quia, Officia, Aut rerum, Qui quo', 14.31);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (19, 'Vitae dolor', 'In neque, Voluptas, Sed, Et et', 22.88);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (20, 'Praesentium et', 'Est est, Nihil et, Officia, Minus', 14.3);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (21, 'Et beatae', 'Dolore, Vitae, Optio, Aut', 27.36);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (22, 'Eligendi sed', 'In, Ea rerum, Sunt, Non', 21.05);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (23, 'Id dolore', 'Molestias, Nihil, Excepturi, Fugiat', 24.46);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (24, 'Deserunt dolor', 'Harum, Accusamus, Et et quo, Eveniet', 18.17);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (25, 'Perspiciatis', 'Et, Beatae, Totam, Magnam', 33.84);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (26, 'Voluptate', 'Explicabo, Debitis, Unde, At minima', 23.67);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (27, 'Recusandae', 'Maiores, Quasi, Dolore, Quia', 32.57);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (28, 'Perspiciatis', 'Qui non, Facere, Voluptas, Quia et', 37.61);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (29, 'Ipsum', 'Vitae cum, Impedit, Qui quod, Magnam', 32.75);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (30, 'Quaerat aut', 'Explicabo, Quaerat a, Aut, Quae enim', 26.29);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (31, 'Dignissimos at', 'Ad et, Ipsam est, Dolore, Dolores', 16.97);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (32, 'Corrupti velit', 'Et aut, Nihil, Et, Dicta', 11.26);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (33, 'Provident', 'Ut quos, Delectus, Est ut, Quis ipsa', 34.29);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (34, 'Exercitationem', 'Est sunt, Sit omnis, Enim, Sit minus', 18.8);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (35, 'Explicabo nemo', 'Et, Atque id, Cum qui, Est quam', 17.84);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (36, 'Reiciendis qui', 'Officia, Et est, Tempore, Ad non', 15.67);
