INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (17, 'Porro beatae', 'Sed qui, Quaerat, Suscipit, Ipsum, ', 15.59);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (18, 'Eos voluptatem', 'Quia, Officia, Aut rerum, Qui quo, ', 14.31);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (19, 'Vitae dolor', 'In neque, Voluptas, Sed, Et et, ', 22.88);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (20, 'Praesentium et', 'Est est, Nihil et, Officia, Minus, ', 14.3);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (21, 'Et beatae', 'Dolore, Vitae, Optio, Aut, ', 27.36);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (22, 'Eligendi sed', 'In, Ea rerum, Sunt, Non, ', 21.05);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (23, 'Id dolore', 'Molestias, Nihil, Excepturi, Fugiat, ', 24.46);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (24, 'Deserunt dolor', 'Harum, Accusamus, Et et quo, Eveniet, ', 18.17);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (25, 'Perspiciatis', 'Et, Beatae, Totam, Magnam, ', 33.84);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (26, 'Voluptate', 'Explicabo, Debitis, Unde, At minima, ', 23.67);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (27, 'Recusandae', 'Maiores, Quasi, Dolore, Quia, ', 32.57);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (28, 'Perspiciatis', 'Qui non, Facere, Voluptas, Quia et, ', 37.61);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (29, 'Ipsum', 'Vitae cum, Impedit, Qui quod, Magnam, ', 32.75);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (30, 'Quaerat aut', 'Explicabo, Quaerat a, Aut, Quae enim, ', 26.29);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (31, 'Dignissimos at', 'Ad et, Ipsam est, Dolore, Dolores, ', 16.97);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (32, 'Corrupti velit', 'Et aut, Nihil, Et, Dicta, ', 11.26);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (33, 'Provident', 'Ut quos, Delectus, Est ut, Quis ipsa, ', 34.29);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (34, 'Exercitationem', 'Est sunt, Sit omnis, Enim, Sit minus, ', 18.8);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (35, 'Explicabo nemo', 'Et, Atque id, Cum qui, Est quam, ', 17.84);
INSERT INTO homestead.pizza (id, pizza, ingredients, price) VALUES (36, 'Reiciendis qui', 'Officia, Et est, Tempore, Ad non, ', 15.67);